# Generated by Django 5.2.5 on 2025-09-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingagency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
