# Generated by Django 5.2.5 on 2025-09-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_staffingagency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingagency',
            name='name',
            field=models.CharField(choices=[('aerotek', 'Aerotek'), ('randstad', 'Randstad'), ('employment_express', 'Employment Express')], max_length=255, unique=True),
        ),
    ]
