# Generated by Django 5.0 on 2025-11-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_alter_staffingagency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingagency',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffingagency',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
