# Generated by Django 5.0 on 2025-12-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_staffingagency_contact_first_name_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingagency',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='organizations.warehousebusiness'),
            preserve_default=False,
        ),
    ]
