# Generated by Django 5.2.5 on 2025-09-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0011_remove_skill_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.TimeField(auto_now_add=True, verbose_name='Clock In')),
                ('clock_out', models.TimeField(auto_now_add=True, verbose_name='Clock Out')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_keeping', to='workers.contractworker', verbose_name='worker')),
            ],
        ),
    ]
