# Generated by Django 5.2.5 on 2025-09-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractworker',
            name='position',
            field=models.CharField(choices=[('forklift_operator', 'Forklift Operator'), ('warehouse_associate', 'Warehouse Associate'), ('material_handler', 'Material Handler')], default='warehouse_associate', max_length=125),
        ),
    ]
