# Generated by Django 5.2.5 on 2025-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_contractworker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractworker',
            name='position',
            field=models.CharField(choices=[('Forklift Operator', 'forklift_operator'), ('Warehouse Associate', 'warehouse_associate'), ('Material Handler', 'material_handler')], default='warehouse_associate', max_length=125),
        ),
    ]
