# Generated by Django 5.2.5 on 2025-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_contractworker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractworker',
            name='position',
            field=models.CharField(choices=[('forklift_operator', 'Forklift Operator'), ('warehouse_associate', 'Warehouse Associate'), ('material_handler', 'Material Handler')], default='Warehouse Associate', max_length=125),
        ),
    ]
