# Generated by Django 5.2.5 on 2025-09-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='abreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='workers.contractworker', verbose_name='Worker'),
        ),
    ]
