# Generated by Django 5.2.5 on 2025-09-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_skill_abreviation_alter_skill_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
