# Generated by Django 5.2.5 on 2025-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_skill_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='color',
        ),
        migrations.AddField(
            model_name='skill',
            name='base_color',
            field=models.CharField(blank=True, default='gray', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
