# Generated by Django 5.2.5 on 2025-09-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_skills', to='workers.skill', verbose_name='Skill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_skills', to='workers.contractworker', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Worker Skill',
                'verbose_name_plural': 'Worker Skills',
                'unique_together': {('worker', 'skill')},
            },
        ),
    ]
