# Generated by Django 5.2.5 on 2025-09-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_remove_skill_certification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='worker',
        ),
    ]
