# Generated by Django 5.2.5 on 2025-09-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('workers', '0011_remove_skill_worker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractworker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterField(
            model_name='contractworker',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='contractworker',
            unique_together={('email', 'current_contract')},
        ),
    ]
