# Generated by Django 5.2.5 on 2025-09-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('workers', '0012_alter_contractworker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_skills', to='organizations.warehousebusiness'),
        ),
    ]
