# Generated by Django 5.2.5 on 2025-09-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='attendance_score',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor')], verbose_name='attendance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='communication_score',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor')], verbose_name='communication'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='performance_score',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor')], verbose_name='performance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='skills_score',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor')], verbose_name='skills'),
        ),
    ]
