# Generated by Django 5.2.5 on 2025-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_attendance_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='attendance_score',
            field=models.FloatField(verbose_name='attendance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='communication_score',
            field=models.FloatField(verbose_name='communication'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='performance_score',
            field=models.FloatField(verbose_name='performance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='skills_score',
            field=models.FloatField(verbose_name='skills'),
        ),
    ]
