# Generated by Django 5.2.5 on 2025-09-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_attendance_score_and_more'),
        ('workers', '0011_remove_skill_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='workers.contractworker', verbose_name='worker'),
        ),
    ]
