# Generated by Django 5.0 on 2025-12-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_rating_worker'),
        ('workers', '0013_skill_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workers.contractworker', verbose_name='worker'),
        ),
    ]
