# Generated by Django 5.0 on 2025-12-09 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_rating_worker'),
        ('workers', '0013_skill_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_rating', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='workers.contractworker', verbose_name='worker'),
        ),
    ]
