# Generated by Django 5.2.5 on 2025-08-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='contract_worker',
            field=models.ManyToManyField(related_name='shifts', to='workers.contractworker', verbose_name='worker'),
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.schedule', verbose_name='schedule'),
        ),
    ]
