# Generated by Django 5.2.5 on 2025-09-29 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('scheduling', '0003_area_manager_remove_shift_position_schedule_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='organizations.warehousebusiness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='organizations.warehousebusiness'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('email', 'organization')},
        ),
    ]
