# Generated by Django 5.2.5 on 2025-09-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_area_organization_manager_organization_and_more'),
        ('workers', '0013_skill_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='contract_worker',
            field=models.ManyToManyField(blank=True, null=True, related_name='shifts', to='workers.contractworker', verbose_name='worker'),
        ),
    ]
