# Generated by Django 5.2.5 on 2025-09-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default='2025-09-25', verbose_name='date'),
            preserve_default=False,
        ),
    ]
