# Generated by Django 5.2.5 on 2025-09-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_shift_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='contract_worker',
            new_name='contract_workers',
        ),
        migrations.AddField(
            model_name='shift',
            name='workers_needed',
            field=models.PositiveIntegerField(default=1, verbose_name='workers needed'),
        ),
    ]
