# Generated by Django 5.0 on 2025-12-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_rename_contract_worker_shift_contract_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='scheduling.area', verbose_name='area'),
        ),
    ]
